
# Note all group ids are not negative
forward:
  - name: grp1
    # forward from & to group id, in int
    from: 1231
    to:   [1232]
    # User ID to watch & forward. If blank, all message will be forwarded
    user: [9871, 9872]
  - name: grp2
    from: 3451
    to:   [3452]
    user: [8761, 8763]

fetch:
  users: [55..6] # 
  command: '/get'
  downloader: youtube-dl
  vformat:  # of youtube-dl -f, --format FORMAT
    - '-f'
    - '18/22'
  folder: '/mnt/tmp'

